### ISSUE TITLE
Help for compiling lib for Freecad

### ISSUE THREAD

**Issue by loszelos** [aewallin/opencamlib#100]
Hello to all, 

is anyone here, who is able to help me and compile lib for the last version of  Freecad for Windows? I spend many time to achieve that and I'm absolutely lost. 
After compile, please attach the file in comment. Thanks :-)  BTW. It would be maybe great to make a folder in repository, or add on release page versions of compiling project. I guess that this can help to many people who is lost with compiling etc. and save many lifes .. :-)

**Comment by vespakoen** [comment]
I think opencamlib is included in Freecad by default?
It seems all you have to do is enable Opencamlib in the settings?

I was only able to see the "Path" preferences when the Path workbench was active.

<img width="2056" alt="Screenshot 2022-11-14 at 13 29 57" src="https://user-images.githubusercontent.com/876117/201660636-8f6f644a-a3d4-436f-816d-6b52939b8154.png">

If you don't see this, try updating Freecad to the latest version.
Also, let me know what platform you are on ;)

**Comment by vespakoen** [comment]
If the above doesn't work, there are now pre-compiled libraries available for Windows, Linux and macOS, please take a look at the new README.
