### ISSUE TITLE
installation on MacOS

### ISSUE THREAD

**Issue by jpkoc** [aewallin/opencamlib#101]
Hi there,
Could you provide (or point me to) detail instructions on how to install OpenCamLib on Mac OS?
Thank you!

**Comment by vespakoen** [comment]
When using opencamlib for Freecad, the newer versions of Freecad include opencamlib by default.

For custom builds / bindings, the most accurate documentation is in the ./scripts folder now.

Let me know if you run into any issues.

**Comment by vespakoen** [comment]
Please take a look at the new readme, installation just got a lot easier.
Let us know if you still run into any issues!
