### ISSUE TITLE
Nodejs test example failing with Segmentation fault error

### ISSUE THREAD

**Issue by maouida** [aewallin/opencamlib#102]
The test.js example included in the repository is failing to work. Error `Segmentation fault`.
I tested with Node `v10.x` and `v16.x` on Ubuntu 22.10
`Cmake version 3.24.2`
The library build was successful.
Any ideas how to fix this?

**Comment by vespakoen** [comment]
Hi @maouida, I changed a bunch of things, please try it again now.
You can also take a look at the scripts in the ./scripts folder.
Also make sure that you run `npm link ../../src/npmpackage` from the 'examples/nodejs' folder before running the scripts.
Will add more documentation for this soon ;)

**Comment by vespakoen** [comment]
Lots of fixes have been made, and in my computer and in CI the node library test works.
Please take a look at the scripts/*-YOUR_PLATFORM.sh scripts, they provide the most accurate documentation on how to install deps, build an run things ;)

Please open a new issue if you still run into any problems.

**Comment by maouida** [comment]
I wanted to write a utility for cutting woodworking joinery, then I realized opencamlib does not implement a pocketing algorithm. I ended up writing a small GCode generator myself, it should not be hard for this specific use case.
