### ISSUE TITLE
Removing boost?

### ISSUE THREAD

**Issue by joemarshall** [aewallin/opencamlib#140]
The build process for this is a real pain if you're anywhere without preinstalled boost everything, because you have to install and compile boost, which is insanely massive and slows everything down build-wise.

Boost is mainly used here for foreach loops, which could be turned into C++11 foreach loops, boost graph library, but in a way that could surely be replaced by pretty straightforward structures, and boost.python, which could be pretty easily replaced with pybind11, which is tiny, and doesn't depend on massive libraries.

**Comment by vespakoen** [comment]
I like the suggestion but I am not sure if anyone is willing to invest the time in doing so.
If you feel like you can do it, go for it, it sure would make things a lot easier.

**Comment by vespakoen** [comment]
Removing Boost would be nice, but it is a huge task. I will not be doing it anyways.
OpenCAMLib also uses the Boost graph library, which is probably also pretty hard to replace with something else.

I also made this "precompiled boost python" project over here: https://github.com/vespakoen/boost-python-precompiled
where you can get a pre-compiled version for your platform / architecture and python version, it hopefully makes things a bit easier.

I'll close this issue for now, but don't let it stop you from trying anyways ;)
