### ISSUE TITLE
CMake problem 

### ISSUE THREAD

**Issue by lhuedepohl** [aewallin/opencamlib#15]
On a current openSUSE Tumbleweed distribution I get an error invoking cmake, see the logs available at https://build.opensuse.org/package/live_build_log/home:lorenz:CAM/opencamlib/openSUSE_Tumbleweed/x86_64

The cmake invocation there is rather verbose. However, I also get the error with just a

```
#> mkdir build
#> cd build
#> cmake ..
-- C++ compiler version: 5.3.1 [/usr/bin/c++]
-- setting gcc options: -Wall  -Wno-deprecated -pedantic-errors
--  CMAKE_BUILD_TYPE = Release
-- Boost version: 1.60.0
-- Found the following Boost libraries:
--   python
-- found Boost: 1_60
-- boost-incude dirs are: /usr/include
-- boost-python lib is: /usr/lib64/libboost_python-mt.so
-- boost_LIBRARY_DIRS is: /usr/lib64
-- Boost_LIBRARIES is: /usr/lib64/libboost_python-mt.so
-- found OpenMP, compiling with flags: -fopenmp
-- OpenCamLib version: 11.10-64-g89c21a2
--  configuring src/cutters
--  configuring src/geo
--  configuring src/algo
--  configuring src/dropcutter
--  configuring src/common
-- CMAKE_INSTALL_PREFIX is : /usr/local
-- Python modules will be installed to: lib/python2.7/site-packages
-- Python libraries will be installed to: lib64/python2.7/site-packages
-- linking python binary ocl.so with boost: /usr/lib64/libboost_python-mt.so
-- Found doxygen. Documentation can be built with 'make doc' 
-- dvips command DVIPS_CONVERTER not found but usually required.
CMake Error at src/CMakeLists.txt:424 (include):
  include could not find load file:

    /home/user/opencamlib/opencamlib/deb/package_details.cmake


-- type:
--  'make' for a normal build
--  'make -j8' to build faster (if you have many cpus)
--  'make install' to install
--  'make package' to build a binary deb-packate
--  'make spackage' to build debian source-packages
--  'make test' to run the tests
-- Configuring incomplete, errors occurred!
```

Incidentally, it seems to work in older versions of openSUSE, see for example the successful log at https://build.opensuse.org/package/live_build_log/home:lorenz:CAM/opencamlib/openSUSE_13.2/x86_64

**Comment by aewallin** [comment]
looking at line 424 of the opencamlib cmakelists.txt it is
include(${CMAKE_SOURCE_DIR}/deb/package_details.cmake)

so is there a change in behaviour between cmake versions or between openSUSE versions that affects where the variable ${CMAKE_SOURCE_DIR}  points?

maybe you could print out that variable just prior to the failing Include-statement?

**Comment by dev-at-stellardeath-org** [comment]
I inserted a `message()` statement:
```
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index c8f8c97..f016b60 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -421,6 +421,7 @@ IF (DOXYGEN_FOUND)
 ENDIF(DOXYGEN_FOUND)
 endif (BUILD_DOC)
 
+message(${CMAKE_SOURCE_DIR})
 include(${CMAKE_SOURCE_DIR}/deb/package_details.cmake)
 
 # "make spackage"
```
Not surprisingly, it prints
```
/home/user/opencamlib/opencamlib
```
that is, the top-level directory, containing the .git folder (sorry for my confusing directory structure with `opencamlib/opencamlib`). This is with cmake version 3.5.2

**Comment by callahanp** [comment]
I can confirm that this is still a a problem.
Ubuntu 16.10 Yakkety
cmake --version
cmake version 3.5.2

Workaround:
copy opencamlib/src/deb directory to opencamlib
then dpkg.

**Comment by aewallin** [comment]
I commented out the change in CMAKE_SOURCE_DIR, this makes it build cleanly on Ubuntu 16.04.
Please open a new issue if there are still problems on other platforms.
