### ISSUE TITLE
Change to a more permissive license to allow linking and distribution

### ISSUE THREAD

**Issue by sliptonic** [aewallin/opencamlib#28]
Since the license change for openvoronoi has gone smoothly, this is a near duplicate issue for OpenCamLib:

FreeCAD already has dropcutter and waterline operations using OCL but the GPL3 license with strong copyleft provisions is too restrictive to allow linking and packaging with applications like FreeCAD that are LGPL.  This means users have to install OCL manually.

If opencamlib was re-licensed LGPL2.1, inclusion in other applications would be easier and interest in using the library would increase.

I'm willing to help with any re-licensing effort and FreeCAD community will help with debian packaging if re-licensed so we can use it.

**Comment by SebKuzminsky** [comment]
I approve of re-licensing my contributions to opencamlib to a more permissive open source license, as chosen by @aewallin and @sliptonic.

**Comment by aewallin** [comment]
I am OK with a change to LGPL2.1

From the insights-page I see the following contributors, in order of commits:
@aewallin (863 klines)
@danheeks (3 klines)
@raoulclais (everyone else << 1 klines)
@SebKuzminsky
@neomilium
@nraynaud
@ianrrees
@sveitser
@fra589
@luzpaz
@ushakov
@DavidNicholls
@lhuedepohl
@ffurano

**Comment by nraynaud** [comment]
I agree to the change.

**Comment by raoulclais** [comment]
I approve of re-licensing my contributions to opencamlib to a more permissive open source license, as chosen by @aewallin and @sliptonic.

**Comment by lhuedepohl** [comment]
I guess for my very small contribution you would not even need my approval. In any case, I agree to re-license my small parts also as LPGL-2.1 or any later version.

**Comment by luzpaz** [comment]
I agree to the change

**Comment by danheeks** [comment]
I agree to the change

**Comment by ianrrees** [comment]
I agree to the change

**Comment by DavidNicholls** [comment]
For what it’s worth,  I also agree.

**Comment by ushakov** [comment]
I also agree.

**Comment by ffurano** [comment]
Hi, I also agree and appreciate very much your efforts

**Comment by aewallin** [comment]
I have just merged #33 and tagged 2018.08
will try to set up travis-ci build (and test?) and maybe readthedocs documentation next.
