### ISSUE TITLE
build docs on readthedocs

### ISSUE THREAD

**Issue by aewallin** [aewallin/opencamlib#32]
use an automated on-line documentation system like readthedocs.

ideally this should build documentation for both the c++ and python APIs, e.g. based on doxygen for c++ and docstrings for python.

**Comment by aewallin** [comment]
now trying this:
https://breathe.readthedocs.io/en/latest/index.html

we first generate an XML file with doxygen.
breathe is then used to convert the XML to sphinx format.
documentation can then be included in sphinx RST-format documentation (how could this be automated?)

currently the readthedocs build fails because it doesn't import breathe:

> ExtensionError: Could not import extension breathe (exception: No module named breathe)
> 
> Extension error:
> Could not import extension breathe (exception: No module named breathe)

**Comment by vespakoen** [comment]
I think this can be closed too =) just need to update the docs now =P

**Comment by aewallin** [comment]
thanks! closing.
