### ISSUE TITLE
Update Launchpad PPA, or create new site for binary release packages

### ISSUE THREAD

**Issue by aewallin** [aewallin/opencamlib#56]
It would be good to have pre-built binaries as a PPA (mainly for Ubuntu, Debian I guess).
Alternatively or additionally some platform that supports win/mac packages would be good too.

There are a couple of existing PPAs - but one well-maintained is better than many poor ones...

- @aewallin last updated in 2012: https://launchpad.net/~anders-e-e-wallin/+archive/ubuntu/cam
- @kkremitzki freecad extras https://launchpad.net/~freecad-community/+archive/ubuntu/ppa
- @neomilium https://launchpad.net/~neomilium/+archive/ubuntu/cam

**Comment by luzpaz** [comment]
yes please

**Comment by m0n5t3r** [comment]
add https://launchpad.net/~iacobs/+archive/ubuntu/cnc/ to the list (it's mine) :)

**Comment by neomilium** [comment]
@aewallin if you want to setup an official PPA:
1. I can help if you need some
2. If your packages work with heekscnc, I can remove packages from mine and point to yours
3. If launchpad support organization or team, I'm OK to share a CAM PPA to merge mine in this one

**Comment by aewallin** [comment]
I added the list of PPAs to the readme-file.

In practice I don't have much time to do maintenance work, and no time to do development work on opencamlib. It would be good if there is a volunteer maintainer who wants to take over.

**Comment by aewallin** [comment]
using pypi from now. closing.
