### ISSUE TITLE
Package on PyPi

### ISSUE THREAD

**Issue by aewallin** [aewallin/opencamlib#57]
The opencamlib python module could/should be distributed on pypi https://pypi.org/

Ideally installing should be as easy as "pip install opencamlib" - on all supported platforms!

**Comment by richieloro** [comment]
It's a very good idea. Is it possible ?

**Comment by Franckapik** [comment]
Is it possible to understand where is the difficulty to have opencamlib on pypi ? 
It could be a great idea to do this...

**Comment by aewallin** [comment]
Thanks to a lot of work by @vespakoen we now have a package on pypi!
https://pypi.org/project/opencamlib/

closing.
