### ISSUE TITLE
i have some trouble with std::isnan(double)' windows

### ISSUE THREAD

**Issue by imzhangzhao** [aewallin/opencamlib#62]
C:/dev/mingw64/include/c++/8.3.1/math.h:66:12: error: 'constexpr bool std::isnan(double)' conflicts with a previous declaration
 using std::isnan;
could you give me some advices?thank you

**Comment by vespakoen** [comment]
It looks similar to this:
https://stackoverflow.com/questions/48513964/cannot-use-c-libraries-that-include-math-h-with-g-7-raspberry-pi

I'd try updating your compiler, or seeing if changing "CMAKE_CXX_STANDARD" to `98` (instead of `11`) in your `src/CMakeLists.txt` file, although this might break other things if this module relies on C++11 features (which I am not sure about).

Good luck!

**Comment by imzhangzhao** [comment]
i have new trouble about python example ---import ocl ,
I make ocl.so    but pycharm cannot find module,Thank you very much for your reply

**Comment by vespakoen** [comment]
You have to put the ocl.so file in the right folder, you should be able to do this after successful compilation by running `make install`

If you are not using make files, perhaps this might work:

```
cmake --build . --target install
```

**Comment by imzhangzhao** [comment]
Iam using ubuntu18.04 now and I had used make install, then ocl.so in /usr/lib/python3/dist-packages,

/usr/bin/python3.6 /home/zhang/opencamlib/examples/python/drop-cutter/batchdropcutter_test_1.py
Traceback (most recent call last):
  File "/home/zhang/opencamlib/examples/python/drop-cutter/batchdropcutter_test_1.py", line 1, in <module>
    import ocl
ImportError: libboost_python36.so.1.69.0: cannot open shared object file: No such file or directory
Process finished with exit code 1

**Comment by vespakoen** [comment]
It cannot find the libboost_python36.so library.

A good place to look how we are building binaries on travis is by looking here: https://github.com/aewallin/opencamlib/blob/master/.travis.yml

Can you post the output of your cmake compilation?

**Comment by imzhangzhao** [comment]
[CMakeOutput.log](https://github.com/aewallin/opencamlib/files/3015812/CMakeOutput.log)

**Comment by imzhangzhao** [comment]
Thank you so much ,The problem was solved after i rebooted the computer
