### ISSUE TITLE
Split into separate pure C++ repo/package + bindings package(s)

### ISSUE THREAD

**Issue by aewallin** [aewallin/opencamlib#63]
As the build system is becoming increasingly complex, maybe it would be good to split the project into a purely C++ part, which seems quite stable over time.

On the other hand the bindings have seen lots of changes, breaking the build etc, and issues with python2 vs python3, which maybe could be handled better in a separate repo focusing on just that particular binding.

Comments? PRs? ;)

**Comment by zachGummow** [comment]
My pull request at [#66](https://github.com/aewallin/opencamlib/pull/66) should make splitting them unnecessary.
