### ISSUE TITLE
[wip] conda-package

### ISSUE THREAD

**Issue by looooo** [aewallin/opencamlib#64]
I created a PR for a conda-package of opencamlib. This won't work out of the box, so help is  needed. Applying the cmake to work with conda-build will also help with getting the cmake more consistent for different platforms.

https://github.com/conda-forge/staged-recipes/pull/8474

**Comment by aewallin** [comment]
is the conda-build OK now?

If your PR is merged at conda-forge, could you update the opencamlib readme with a short instruction on how to use/install using conda?
thanks.

**Comment by looooo** [comment]
It would be nice to use a release for the recipe. Currently it's using the master branch. Using a release allows automated PR for future releases which is a very nice feature.

Once done I can add some instruction on how to install ocl via conda.

**Comment by looooo** [comment]
@aewallin are you planning a release? The conda-builds are working now but are still using boost 1.68. Most of the conda-packages are now updated to boost 1.70. So it would be nice if ocl could update to boost1.70 too. The error reported when using boost 1.70 can be found here: https://github.com/conda-forge/staged-recipes/pull/8474#issuecomment-497690901

**Comment by aewallin** [comment]
I am using Ubuntu 18.04 LTS and it comes with boost 1.65 (or 1.65.1?)

I don't know what to do about the error you linked above. The first one seems to be about linking the executable after build, and the other about boost-python not passing pedantic-mode of gcc?

In general I would expect the ocl c++ code to build with many different boost-versions - unless there really are API-changes in boost?

there was already some cleanup/simplification of the cmake-scripts - but more wouldn't hurt...

I am not working very actively on ocl lately - but a new release shouldn't be that much work, if it helps to solve something..

**Comment by looooo** [comment]
> In general I would expect the ocl c++ code to build with many different boost-versions - unless there really are API-changes in boost?

You are right, it seems ` -D Boost_NO_BOOST_CMAKE:BOOL=ON ` did the trick for boost 1.70.

> I am not working very actively on ocl lately - but a new release shouldn't be that much work, if it helps to solve something..

any release would help a lot.

**Comment by looooo** [comment]
> I am not working very actively on ocl lately - but a new release shouldn't be that much work, if it helps to solve something..

@aewallin How is the status of the upcoming release?

**Comment by aewallin** [comment]
I have now opened an issue #71 to discuss the new release.

@looooo can you confirm what is needed for the new release wrt. to a conda package in the #71 discussion-thread - thanks.

I should have time to push this forward now in July.

**Comment by looooo** [comment]
Something went wrong with the release:

```
CMake Error at version_string.cmake:39 (file):
  file failed to open for reading (No such file or directory):
```

Is there a subrepo required?

**Comment by aewallin** [comment]
the idea is to set the version to the result of "git describe --tags"
if it finds a git executable it tries that, but if it isn't in a git repo
it will fail.
there was some failover mechanism with the git-tag.txt file, but I don't
remember how exactly it was supposed to work.

in my git-repo I get:
$ git describe --tags
2019.07

**Comment by looooo** [comment]
So better use the git tag?

**Comment by waebbl** [comment]
You have an option VERSION_STRING in the `src/CMakeLists.txt` file which you can pass to cmake, for example to build a package from the tarball where you don't have a git repo.

**Comment by looooo** [comment]
@waebbl thanks this worked:
https://github.com/conda-forge/opencamlib-feedstock/blob/master/recipe/build.sh#L16

**Comment by looooo** [comment]
and finally opencamlib is now on conda-forge:
https://github.com/conda-forge/opencamlib-feedstock

thanks everyone for the help! :tada:
