### ISSUE TITLE
dependancy on current cmake for python 3

### ISSUE THREAD

**Issue by ErichBSchulz** [aewallin/opencamlib#70]
An FYI for others struggling to compile on a python 3 version.

I failed all afternoon until I upgraded my cmake.

cmake 3.10 was broken, but cmake 3.14 worked

**Comment by aewallin** [comment]
In the cmake-files I have now bumped the minimum version required to 3.14.
this does require using the kitware PPA to get the latest cmake on my 18.04LTS machine.

closing this - open new issues if there are still problems - thanks.
