### ISSUE TITLE
2019 July release

### ISSUE THREAD

**Issue by aewallin** [aewallin/opencamlib#71]
This issue is to discuss the work needed for a new release in July 2019.

- [ ] build is currently broken - is this a real or a travis issue?
- [ ] we have 3 open pull-requests by @vespakoen - do we wait&merge or skip these?
- [ ] the cmake build system has grown complex - do we change this now or later?
- [x]  cmake minimum version bumped to 3.14. use the kitware PPA to get latest cmake if needed.

any other issues before a release?

**Comment by looooo** [comment]
For the conda-forge package everything should be fine (I will test again once the master is ready for the release). The only thing needed for the conda-forge package is a release.

**Comment by looooo** [comment]
I uploaded a package from current master to anaconda.org (linux and osx). If someone wants to give it a try:

```
conda install opencamlib -c freecad/label/dev
```

**Comment by aewallin** [comment]
2019.07 now tagged.

I may or may not have time/energy to look at a PPA for binary distribution.
I really think the cmake build with all the bindings needs to be simplified a lot as the next step.
