### ISSUE TITLE
DropCutter memory leak

### ISSUE THREAD

**Issue by coburnw** [aewallin/opencamlib#78]
I have been playing with the OCL_DropCutter algorithm using a Rotational Scantype in FreeCAD's Path module with significant memory loss.  Conversely, with a Planer Scantype, only minor memory loss. It seems that a new instance of the dropcutter is run for each of the rotational scans, which if the model is of any significance can be many.

To test the DropCutter I load a simple model in FreeCAD and use linux pmap to record the process memory before and after a run and am fairly confident the DropCutter memory handling is better now than it was.  

My only experience with OCL is thru FreeCAD and with that i am still an amateur.  Maybe others with more experience than i can verify the algorithms are still producing good data after these changes.

Coburn

**Comment by aewallin** [comment]
can you re-build now that #79 and #80 are merged - and test again?

If there are automatic ways of testing for memory-leaks then we should try to include them in the automated travis-testing.

**Comment by coburnw** [comment]
Cloned and built the master branch of aewallin/ocl repository.

 pmap shows FreeCAD's memory usage from path run to run to be more appropriate now.  

The path module also seems to output gcode that looks the same between both the old and new version of the library.  I think this is a step forward.

**Comment by aewallin** [comment]
thanks for testing.
closing this for now, please re-open or submit a new issue if you find more memory leaks or issues!
