### ISSUE TITLE
compilation error after Merge pull request #81 from gwicke/liftZ_race

### ISSUE THREAD

**Issue by fred2020-net** [aewallin/opencamlib#82]
@aewallin @gwicke 

Hello and thanks for this amazing library. Up from today I could compile it successfully in windows (VS2015).
I updated the code with this PR#81 and now i got issues in 2 following files at compilation (still in VS2015).
Thanks if you can help me to understand the issue. it is related to the usage of atomic and operator=.

- in clpoint.cpp

	CLPoint& CLPoint::operator=(const CLPoint &clp) {
		if (this == &clp)   // check for self-assignment
			return *this;
		x = clp.x;
		y = clp.y;
		z = clp.z;
		if (cc) { //compile error: more than one conversion function from "std::atomic<ocl::CCPoint *>" to a built-in type applies:
				// function "std::atomic<_Ty *>::operator _Ty *() const [with _Ty=ocl::CCPoint]"
				//  function "std::_Atomic_address::operator void *() const"
			delete cc.load();
		}
		cc = new CCPoint(*(clp.cc));
		return *this;
	}

- compositecutter.cpp

	//********   facetDrop  ********************** */

	// call facetDrop on each cutter and pick a valid cc-point
	bool CompositeCutter::facetDrop(CLPoint &cl, const Triangle &t) const {
		bool result = false;
		for (unsigned int n = 0; n<cutter.size(); ++n) { // loop through cutters
			CLPoint cl_tmp = cl + CLPoint(0, 0, zoffset[n]);
			CCPoint* cc_tmp;
			if (cutter[n]->facetDrop(cl_tmp, t)) {
				assert(cl_tmp.cc != nullptr); //compile error: C2593	'operator !=' is ambiguous
				if (ccValidRadius(n, cl_tmp)) { // cc-point is valid
					cc_tmp = new CCPoint(*cl_tmp.cc);
					if (cl.liftZ(cl_tmp.z - zoffset[n])) { // we need to lift the cutter
						cc_tmp->type = FACET;
						cl.cc = cc_tmp;
						result = true;
					}
					else {
						delete cc_tmp;
					}
				}
			}
		}
		return result;
	}

**Comment by gwicke** [comment]
When searching for the C2593 error code, there are quite a few discussions about MSVC not using the standard C++ overload resolution when using /permissive mode. I see no match for `permissive` in the opencamlib source.

Could you check if /permissive is potentially used in your case?

**Comment by fred2020-net** [comment]
Hi @gwicke and thanks for your feedback.
I use VS2015. It seems that `/permissive` is valid only for VS2017 and upper.

Moreover, I searched in the compiler settings and didn't found any /permissive flag.

**Comment by gwicke** [comment]
@fred2020-net, from the few doc I linked above, it seems that "permissive" mode was actually the default in older versions of MSVC, with only newer versions supporting C++11 compliant mode (and the flag). 

We can see if there is a work-around we can apply here to help non-standard compilers.

**Comment by fred2020-net** [comment]
@gwicke 

I did the following change in clpoint.cpp

	CLPoint& CLPoint::operator=(const CLPoint &clp) {
		if (this == &clp)   // check for self-assignment
			return *this;
		x = clp.x;
		y = clp.y;
		z = clp.z;
		if (cc.load() != 0) { // was if (cc!= 0)  { //error C2593: 'operator !=' is ambiguous
			delete cc.load();
		}
		cc = new CCPoint(*(clp.cc));
		return *this;
	}


It compiles now in VS2015. 
But I don't know if it's correct to replace cc by cc.load().
Because from what I understand we are testing here if the atomic pointer exists and not if its content (pointer to CLPoint) exists.

Thanks to clarify if my fix is correct or not.

**Comment by fred2020-net** [comment]
@gwicke 
Hello please can you confirm that my change proposed in my previous comment is correct 

replacing

`if  (cc != 0)`

by

`if  (cc.load() != 0)`


Thank you

**Comment by fred2020-net** [comment]
Hello
Compiles correctly in VS2019 without changing code mentioned in my last post.
