### ISSUE TITLE
VS2019 compilation warning

### ISSUE THREAD

**Issue by fred2020-net** [aewallin/opencamlib#86]
Hello,

I get a warning when compiling on VS2019, that was not when previously compiling in VS2015.

smart_weave.cpp
##[warning]src\algo\smart_weave.cpp(338,33): Warning C4834: discarding return value of function with 'nodiscard' attribut

`for(    in_edge_itr = in_edges.begin(),    out_edge_itr = out_edges.begin();  ` 
`           in_edge_itr < in_edges.end(),    out_edge_itr < out_edges.end();  ` 
`           in_edge_itr++,                    out_edge_itr++ )  ` 

in 2nd line of code
**in_edge_itr < in_edges.end()** with the operator <

What is the consequence ? Can someone have an idea for a fix ?

Thank you

**Comment by vespakoen** [comment]
It seems to work fine in spite of this error, but I will take a look at fixing this soon.
Thanks for reporting!
