### ISSUE TITLE
How to build the lib used for python project

### ISSUE THREAD

**Issue by 1127378627** [aewallin/opencamlib#89]
I cannot make a lib for python, anyone can do this job?

**Comment by aewallin** [comment]
what platform are you on?
what did you try and what error message did you get?

on travis it looks like all linux build variants are working: https://travis-ci.org/github/aewallin/opencamlib

**Comment by 1127378627** [comment]
Win10 X64，Intel(R) Core(TM) i5-9300H CPU.&nbsp; I want to use opencamlib in my pythonOCC project, Python 3.6 or Python 3.7. Do you have any suggestions? Is possible to use the python lib which complied in linux systerm or must build on Win10, that I can use the opencamlib in python like this: import opencamlib, ...






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aewallin/opencamlib"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月24日(星期四) 凌晨2:41
收件人:&nbsp;"aewallin/opencamlib"<opencamlib@noreply.github.com&gt;;
抄送:&nbsp;"发帖人体"<1127378627@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [aewallin/opencamlib] How to build the lib used for python project (#89)





 
what platform are you on?
 what did you try and what error message did you get?
 
on travis it looks like all linux build variants are working: https://travis-ci.org/github/aewallin/opencamlib

**Comment by aewallin** [comment]
You need to build the python module under Windows in order to import in a windows python environment.

One alternative to visual studio could be the cygwin environment (https://www.cygwin.com/) - which should allow building opencamlib in a very similar environment to native linux.
If travis supports cygwin this would be a good addition to the automatic travis builds.

**Comment by vespakoen** [comment]
We now have pre-compiled OpenCAMLib libraries for Windows, macOS and Linux (Python V3.7 - v3.11), it should be as simple as:

```shell
pip install opencamlib
```
