### ISSUE TITLE
Building on FreeBSD

### ISSUE THREAD

**Issue by denverh2000** [aewallin/opencamlib#96]
Hello,

FreeBSD reserves locations like /usr/include, /usr/lib for the base system.  Everything else goes into /usr/local.  When I first tried building ocl I got errors about missing boost header files.  I could fix those errors by temporarily creating a symbolic link to /usr/local/include/boost in /usr/include.  It would be better if ocl could find the necessary libraries and headers in /usr/local, but I'm not sure how to get that done.

Thanks,

Denver

**Comment by aewallin** [comment]
cmake (https://cmake.org/) should support FreeBSD, however I don't have a FreeBSD system to test on.

If you are eager to get this working then I guess read the cmake documentation and how/if cmake-scripts should be modified to better support FreeBSD.

The opencamlib build has grown quite complex - it would be good to separate it into a bare C++ library (perhaps including python bindings) and have all the rest as separate builds.

**Comment by denverh2000** [comment]
cmake works fine with FreeBSD.  Lots of other projects use it and build with no problem.  What I found was that it was choosing the base system compiler (/usr/bin/c++), which specifically does not search /usr/local.  I added "-DCMAKE_C_COMPILER=/usr/local/bin/gcc" to the cmake command.
